name: flake8 Lint

on:
  pull_request:
    branches: [ master, future ]
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out Pixray code
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: flake8 Lint
        uses: py-actions/flake8@v2